### PR TITLE
Add windows build

### PR DESCRIPTION
**Pull request by daniel88ferreira**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by daniel88ferreira** [comment]
@conda-forge-admin, please rerender

**Comment by daniel88ferreira** [comment]
@conda-forge-admin, please rerender

**Comment by daniel88ferreira** [comment]
@conda-forge-admin, please restart ci

**Comment by daniel88ferreira** [comment]
Hello @CJ-Wright @scopatz @thewchan 
This PR is to add builds for windows also, please take look :)
Thanks!

**Review by thewchan — APPROVED** [review]
This looks good to me but waiting for others to weigh in

**Comment by daniel88ferreira** [comment]
@CJ-Wright @scopatz friendly reminder.
Please take a look and approve if you this this is fine

**Comment by daniel88ferreira** [comment]
@thewchan  do you know if there’s something we can do to get this reviewed and merged?
@CJ-Wright @scopatz 

thanks in advance

**Pull request merged**
